### ISSUE TITLE
Is there a way to increase the bit rate?

### ISSUE THREAD

**Issue by Arsenicss** [TheGoddessInari/netflix-1080p-firefox#11]
Hello friends, I just tested it on my device. Fortunately, it can be forced to 1080P, but the video stream only has HPL (High@L4) without MPL (Main@L4).
There is no cbr encoding in hpl, which leads to a very low bit rate of the video, but I can see that there is an MPL video stream in your screenshot...how to do it!!

manifest: [Test Patterns S01E01](https://s3.ax1x.com/2021/01/05/skvIhR.png)

**Comment by TheGoddessInari** [comment]
Could you please confirm that videos even have a main profile, or that this actually increases quality?

I was adding this, and no videos would work without avchigh or VP9.

**Comment by Arsenicss** [comment]
> Could you please confirm that videos even have a main profile, or that this actually increases quality?
> 
> I was adding this, and no videos would work without avchigh or VP9.

It is certain that the video exists in the Main profile. MPL can be played through playready in the edge, but it is not available in widevine. This problem has troubled me for a long time and I don't know how to solve it.

**Comment by TheGoddessInari** [comment]
Well, then realistically there's nothing I can do about that if it's not supported by any DRM other than what Microsoft insists on alone. Disabling AVChigh profiles + VP9 returns "title unavailable to stream online" for everything, including previews.
