### ISSUE TITLE
Stopped doing 1080p

### ISSUE THREAD

**Issue by kroeckx** [TheGoddessInari/netflix-1080p-firefox#14]
1080p was working for a very long time, but now everything seems to be 720p.

**Comment by Termuellinator** [comment]
see https://github.com/TheGoddessInari/netflix-1080p-firefox/issues/13 (lower down, ignore the behaviour of the initial reporter ;) )

**Comment by TheGoddessInari** [comment]
This is fixed in 1.15.3, and was a duplicate of #13 anyway.
