### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by CapoFantasma97** [TheGoddessInari/netflix-1080p-firefox#15]
> As mentioned in the description, filing and contributing issues is more useful than leaving a negative review when Netflix changes something big on their end that takes time to figure out.

But there's nothing in the description or anywhere else to contact you or see this Github page. In the end, I started digging around and found this.

Maybe if you add a contact or this page's URL to the description (in a way that's clearly visible), you'd get a lot less negative/average reviews that are made to get your attention anyway.

**Comment by maniackcrudelis** [comment]
Just below the reviews,
More information > Add-on Links

Homepage and Support site both link directly here, which is a good way to come here and see what's going on, and the main dev was working on it in https://github.com/TheGoddessInari/netflix-1080p-firefox/issues/13.

Considering the description says "Also get in touch for any issues whatsoever, please", that sounds like a good idea to have a look to the links for the add-on.

I was myself angry when it didn't work anymore, primarily against Netflix though, but actually Netflix didn't do anything to fix it, @TheGoddessInari did !

**Comment by georgeat8** [comment]
I don't see so many negative reviews whatsoever and the links are posted based on Firefox Extensions website UI/UX, they don't need to be all over the place if there is a spot specifically made for them.

**Comment by CapoFantasma97** [comment]
> I don't see so many negative reviews whatsoever and the links are posted based on Firefox Extensions website UI/UX, they don't need to be all over the place if there is a spot specifically made for them.

There's also only 85 reviews, of which all of the negative ones, most of the "neutral" ones and some of the 5 star ones contain complaints of the addon not working. And there's only 3 Issues other than mine in this Github, so I'm pretty sure most people don't have any idea where to request help.

But whatever, this can be closed now.

**Comment by TheGoddessInari** [comment]
I honestly think that assuming extension users can't find where to report issues is rather silly. It's featured very prominently on AMO where to request support. It even lists my personal email.
