### ISSUE TITLE
Bit-rate

### ISSUE THREAD

**Issue by ItooDesp** [TheGoddessInari/netflix-1080p-firefox#16]
Hi,

Is is possible to adjust the Video bit-rate?

For example, on vikings on Firefox I am only able to watch 1080p with 1117 bit-rate.
But when I use the windows 10 app I get to stream 1080p with 3363 bit-rate and a much sharper image.

Thanks for all your work, time and effort put into this. It its truly very much appreciated .

**Comment by georgeat8** [comment]
If you press `CTRL+ALT+SHIFT+S` it should open up a menu where you can select from all the possible bitrates. Also, disabling VP9 decoding from the add-on settings might give you a better bitrate selection.

**Comment by ItooDesp** [comment]
Indeed ! disabling VP9 decoding worked ! Thank you very much for the tip.
