### ISSUE TITLE
Test Patterns 1080p but movies 540p

### ISSUE THREAD

**Issue by richexx** [TheGoddessInari/netflix-1080p-firefox#24]
The test video shows 1080p, but all movies seem to be stuck to 540p. Any hints?

**Comment by TheGoddessInari** [comment]
Does the problem of 540p only occur with the extension enabled?

**Comment by richexx** [comment]
I can't disable the extension. Had to uninstall it and clear data, otherwise I get an error. With the extension uninstalled I get 720p with the test patterns and 540p with the movies.

**Comment by TheGoddessInari** [comment]
It sounds like a duplicate of #1 then.
In general, if it hits 540p, it's one of the "Hollywood Movies", and apparently that's what they push.

**Comment by richexx** [comment]
What you say is correct. Some movies are pushed @ 540p, some @720p and the ones being pushed @1080p are working great. Closing the issue.
