### ISSUE TITLE
2.0 sound source does not work with ad-on enabled

### ISSUE THREAD

**Issue by 1MikeKramer** [TheGoddessInari/netflix-1080p-firefox#25]
This add-on has been fantastic, Thanks for all your work on it.
But yesterday I suddenly started having an odd issue with it, I was watching a show and had the audio set to a non native language in 2.0 sound and it worked fine like normally, then that evening when I went back to finish the show I found that only 5.1 audio sources would work but 2.0 sound sources have no audio

I tested a few different shows and all had the same result, 5.1 sound works normally, but if I change to a 2.0 sound source there is no sound at all.

Turning off the add-on in Firefox makes the sound work normally in the default Netflix settings ( No 5.1 surround options )

**Comment by TheGoddessInari** [comment]
I'm guessing you're using the 5.1 audio checkbox, and expecting stereo to work as an instant swap. 
Netflix controls that part of things, and it appears that merely exposing 5.1 as a capability ruins the player's ability to do stereo.
Uncheck the box. :)

**Comment by TheGoddessInari** [comment]
On my tests, this started working. I can switch between all formats and languages with 5.1 checked now.
