### ISSUE TITLE
Error M7336

### ISSUE THREAD

**Issue by xcasxcursex** [TheGoddessInari/netflix-1080p-firefox#5]
In the past few days, I've found hat some titles are failing to play, and I am returned to an error screen with code M7336.

Disabling this addon resolves that. I tried rolling back to the older version, and it's not working either.  [This title works]( https://www.netflix.com/watch/80018585)... [This one doesn't](https://www.netflix.com/watch/60000521).

**Comment by TheGoddessInari** [comment]
Working on a fix for this. With luck, will have it fixed perfectly within a few hours.

**Comment by TheGoddessInari** [comment]
Try 1.13 on AMO.

What was happening was that Netflix removed the "Edge" special case, so for example it'd fall back from VP9 to a non-existent Edge-specific resource.

**Comment by xcasxcursex** [comment]
Great work, getting 1080p here on the above link that didn't work :)
Thanks man!
