### ISSUE TITLE
Addon blocks Widevine on Netflix when addon disabled

### ISSUE THREAD

**Issue by maxarmin** [TheGoddessInari/netflix-1080p-firefox#6]
Windows version: **Windows 10 Pro 1909**
Firefox version: **Version 77.0.1 (64-bit)**
Addon version: **1.13** (latest from Firefox Store)

Problem:
When the addon is disabled, it blocks Widevine from running on Netflix only, even after caches and cookies have been erased and removed. Uninstalling the addon would result in the same way. Other websites that uses Widevine DRM works as usual.

Ways to reproduce:
1- Install the addon.
2- Open Netflix and try to watch any shows or movies. It will allow 1080p streams.
3- Disable the addon. You will notice that even when Widevine is installed for Firefox (can be verified at about:addons#plugins), you will get this picture:
![image](https://user-images.githubusercontent.com/41212051/85477172-720da080-b5c2-11ea-8309-0b684bc997f9.png)

Temporary solution:
**Either clear the browser cache or reinstall Firefox.**

Note:
- Even if the playback settings (quality) in Netflix account section is set to Low, the videos will still be forced to run at 1080p.

**Comment by TheGoddessInari** [comment]
Apologies for the delay in responding. The gist is, addon rewrites a script, but Firefox caches that result.

I'm not aware of a way to tell Firefox that it shouldn't actually cache the response that the addon generates? If there is, I'll be happy and fix it.

If there are other ways to deal with this, I'm happy to learn about it.

**Comment by TheGoddessInari** [comment]
This should be fixed in fe51668, which is a part of v1.14.0.
Let me know, please.
