### ISSUE TITLE
Remove VP9 profiles for higher bitrates

### ISSUE THREAD

**Issue by DavidBuchanan314** [TheGoddessInari/netflix-1080p-firefox#7]
I'm using release 1.13 from the firefox addon website.

By default, the `vp9-profile0-L40-dash-cenc` ends up getting used, and I get mediocre bitrates (~1000kbps).

If I remove all the vp9 profiles from the list, the manifest API responds with the `playready-h264*-dash` profiles, of which the `playready-h264hpl40-dash` has the best bitrates (~6000kbps).

I imagine this behaviour might change over time, or for different titles, so perhaps a "enable VP9 profiles" settings toggle should be added?

**Comment by TheGoddessInari** [comment]
Sorry for the delay here; I was going to make VP9 optional anyway (even though apparently Netflix is now pushing VP9 to Firefox even without the extension), but you do realize the entire point of VP9 is to encode better? In other words, you should be seeing the same quality, just at a lower bitrate with VP9.

The main reason to disable VP9 AFAIK isn't quality but lack of hardware decoding.

Do you happen to have a (US) example of a title with very high 1080p H.264 bitrate?

**Comment by TheGoddessInari** [comment]
1.14 will have the option, whenever Mozilla lets me log in to publish it.

**Comment by DavidBuchanan314** [comment]
Yes, I hear VP9 has about 50% better compression ratio for equivalent quality, so if the h264 bitrate is >50% higher then it should be "worth it".

On UK Netflix (sorry I can't test from US), For Breaking Bad S01E01 I get 5423kbps h264 (playready-h264hpl40-dash), compared to 2280kbps VP9 (vp9-profile0-L40-dash-cenc).

(https://www.netflix.com/watch/70196252)

**Comment by TheGoddessInari** [comment]
Fixed with 1.14, which was forever ago, at this point. 🦊
