### ISSUE TITLE
Error when skipping intro and playing after pausing

### ISSUE THREAD

**Issue by wydwww** [TheGoddessInari/netflix-1080p-firefox#8]
Hi developer,

This addon does support 1080p with Firefox on macOS, but I found another issue: when I pause the video then play, or skip intro (click then button), Netflix will show an error page with error code F7375.
I am using the latest version from Firefox add-on store.

I also tried https://github.com/truedread/netflix-1080p (version 1.19) on Brave browser. There is no such pause and play issue using version 1.19.

**Comment by TheGoddessInari** [comment]
Please see if this is still the case. Since Apple believes in walled gardens, there's no way for me to test or develop specifically for the platform.
